repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
